version: '3'
services:
  wp:
    image: wp
    volumes:
      - wordpress:/var/www/html/
    ports:
      - 80:80
    networks: 
      - wp    

  mysql:
    image: mysql
    volumes:
      - sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: wp
    ports:
      - 3306:3306
    networks: 
      - wp    
volumes:
  wordpress:
  sql: 
networks:
  wp:  
